apiVersion: v1
kind: Service
metadata:
  name: { { include "service1.fullname" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector:
    app: { { include "service1.name" . } }
