apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx # Use this instead of deprecated annotation
  rules:
    - host: api.test.com
      http:
        paths:
          - path: /api/track/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service1
                port:
                  number: 9091
          - path: /api/data/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service3
                port:
                  number: 9094
