apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: service1
          image: ghcr.io/aditi-git/service1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
